    
version: '3'
services:  
  db:
    image: postgres:10
    restart: always
    ports:
     - 5432:5432   
    container_name: 'mynewdb'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA : /var/lib/postgresql/data/PostgresData
      POSTGRES_DB : newdb
  web: 
    build: .
    container_name: 'myweb'    
    links: 
      - db   
    restart: always
    ports: 
      - 5000:80 
    depends_on: 
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: mynginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    restart: always
    ports: 
      - 80:80
  